### ISSUE TITLE
Enhancement of kcat integration in protocol.m 

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#224] opened 2023-02-21 09:22 UTC
https://github.com/SysBioChalmers/GECKO/blob/6c0dae90306810fdbd9501109f9b43a967a00646/tutorials/protocol.m#L113

Would be better to indicate what users should do if they only have run step (1) **or** (2), particularly for those who cannot successfully go through DLKcat predictions.

**Comment by edkerk** [comment] 2023-02-21 10:10
Indeed, protocol.m is at the moment a sketch for internal use, this will be clarified and aligned (numbered) with the procedure text.

**Comment by edkerk** [comment] 2023-02-28 01:09
In essence duplicate of #236

**Closed by edkerk** 2023-02-28 01:09 UTC
Labels: enhancement, gecko3
